version: '3.3'
services:
  clickhouse-1:
    container_name: clickhouse-1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - '9000:9000'
      - '8123:8123'
    image: yandex/clickhouse-server
